# Generated by Django 3.0.5 on 2020-04-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AviasalesSearchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.IntegerField(default='0')),
                ('input_data', models.TextField(default='')),
                ('output_data', models.TextField(default='')),
                ('is_loading_failed', models.BooleanField(default=False)),
                ('current_status', models.CharField(default='new', max_length=8)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_request', models.DateTimeField(auto_now_add=True)),
                ('departure_country', models.CharField(choices=[('RU', 'Россия'), ('BY', 'Беларусь'), ('KZ', 'Казахстан'), ('ANY', 'Другие страны')], default='RU', max_length=3)),
                ('departure_city', models.CharField(choices=[('Москва', 'Москва'), ('Казань', 'Казань'), ('Сочи', 'Сочи')], default='Москва', max_length=60)),
                ('date_of_departure', models.DateField()),
                ('changing_the_departure_date', models.CharField(choices=[('0', 'Без отклонения'), ('1', '1 день(+/-)'), ('2', '2 день(+/-)'), ('3', '3 день(+/-)')], default='0', max_length=1)),
                ('destination_country', models.CharField(choices=[('Таиланд', 'Таиланд'), ('Россия', 'Россия'), ('Турция', 'Турция'), ('Индонезия', 'Индонезия'), ('Греция', 'Греция')], default='Таиланд', max_length=20)),
                ('destination_resort', models.CharField(choices=[('Любой', 'Любой'), ('Бали', 'Бали'), ('Пхукет', 'Пхукет'), ('Родос', 'Родос'), ('Сиде', 'Сиде')], default='Любой', max_length=60)),
                ('hotel_name', models.CharField(blank=True, max_length=60, null=True)),
                ('count_of_hotel_stars', models.CharField(choices=[('0', 'Не важно'), ('2', '2 звезды'), ('3', '3 звезды'), ('4', '4 звезды'), ('5', '5 звезд')], default='0', max_length=1)),
                ('hotel_rating', models.CharField(choices=[('0', 'Не важно'), ('5', '5 и более'), ('6', '6 и более'), ('7', '7 и более'), ('8', '8 и более'), ('9', '9 и более')], default='0', max_length=1)),
                ('type_of_food', models.CharField(choices=[('0', 'Не важно'), ('2', 'BB - Только завтрак'), ('3', 'HB - Завтрак и ужин'), ('4', 'FB - трех разовое питание'), ('5', 'AL - Все включено')], default='0', max_length=1)),
                ('return_date', models.DateField()),
                ('changing_return_date', models.CharField(choices=[('0', 'Без отклонения'), ('1', '1 день(+/-)'), ('2', '2 день(+/-)'), ('3', '3 день(+/-)')], default='0', max_length=1)),
                ('number_of_adults', models.CharField(choices=[('1', '1 взрослый'), ('2', '2 взрослых'), ('3', '3 взрослых'), ('4', '4 взрослых'), ('5', '5 взрослых'), ('6', '6 взрослых')], default='2', max_length=1)),
                ('number_of_children', models.CharField(choices=[('0', 'Без детей'), ('1', '1 ребенок'), ('2', '2 ребенка'), ('3', '3 ребенка'), ('4', '4 ребенка')], default='0', max_length=1)),
                ('number_of_infants', models.CharField(choices=[('0', 'Без грудных детей'), ('1', '1 грудной ребенок'), ('2', '2 грудных ребенка'), ('3', '3 грудных ребенка')], default='0', max_length=1)),
                ('direct_flights_only', models.BooleanField()),
                ('accommodation_at_the_hotel_only', models.BooleanField()),
                ('is_loading_ended', models.BooleanField(default=False)),
                ('is_loading_failed', models.BooleanField(default=False)),
                ('aviasales_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_task', to='tour.AviasalesSearchTask')),
            ],
        ),
    ]
